import type { IUser } from "./interfaces/IUser";


export const USERS: IUser[] = [
  {
    "id": 1,
    "login": "midi",
    "isActive": true,
    "avatar": "/src/assets/images/avatar.png",
    "gender": true,
    "email": "chloe.robinson@example.com",
    "phone": "71191281058",
    "country": "Россия",
    "role": "Администратор",
    "dateOfBirth": "30.08.2003",
    "dateOfRegistration": "01.09.2021",
    "totalOrders": 9,
    "totalRevenue": 87794,
    "fullName": "Чернов Михаил Ильич"
  },
  {
    "id": 2,
    "login": "h0riz4n",
    "isActive": true,
    "avatar": "/src/assets/images/avatar-rust.jpg",
    "gender": true,
    "email": "example@example.com",
    "phone": "71191281058",
    "country": "Россия",
    "role": "Администратор",
    "dateOfBirth": "18.05.2003",
    "dateOfRegistration": "01.09.2021",
    "totalOrders": 9,
    "totalRevenue": 87794,
    "fullName": "Худоян Рустам Ширинович"
  },
  {
    "id": 3,
    "login": "john_doe",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/1.jpg",
    "gender": false,
    "email": "mason.lee@example.com",
    "phone": "73613509603",
    "country": "Казахстан",
    "role": "Покупатель",
    "dateOfBirth": "01.01.2001",
    "dateOfRegistration": "06.03.2021",
    "totalOrders": 16,
    "totalRevenue": 13920,
    "fullName": "Карпова Екатерина Ильинична"
  },
  {
    "id": 4,
    "login": "newlogin",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/3.jpg",
    "gender": false,
    "email": "emily.wilson@example.com",
    "phone": "77521379998",
    "country": "Армения",
    "role": "Заблокирован",
    "dateOfBirth": "02.11.2001",
    "dateOfRegistration": "31.10.2020",
    "totalOrders": 12,
    "totalRevenue": 7788,
    "fullName": "Антонова Екатерина Владимировна"
  },
  {
    "id": 5,
    "login": "guestuser",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/2.jpg",
    "gender": false,
    "email": "lucas.roberts@example.com",
    "phone": "77925609385",
    "country": "Другая",
    "role": "Покупатель",
    "dateOfBirth": "08.06.2009",
    "dateOfRegistration": "16.10.2020",
    "totalOrders": 16,
    "totalRevenue": 23744,
    "fullName": "Федоров Владислав Сергеевич"
  },
  {
    "id": 6,
    "login": "admin1",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/2.jpg",
    "gender": true,
    "email": "ryan.garcia@example.com",
    "phone": "76094988764",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "15.05.2004",
    "dateOfRegistration": "09.04.2022",
    "totalOrders": 8,
    "totalRevenue": 30516,
    "fullName": "Андреев Алексей Дмитриевич"
  },
  {
    "id": 7,
    "login": "tech123",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/3.jpg",
    "gender": false,
    "email": "grace.hall@example.com",
    "phone": "86983215827",
    "country": "Армения",
    "role": "Заблокирован",
    "dateOfBirth": "25.10.2000",
    "dateOfRegistration": "16.03.2023",
    "totalOrders": 5,
    "totalRevenue": 43220,
    "fullName": "Петров Александр Сергеевич"
  },
  {
    "id": 8,
    "login": "janedoe",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/4.jpg",
    "gender": true,
    "email": "zoey.adams@example.com",
    "phone": "77186974540",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "01.06.2006",
    "dateOfRegistration": "26.06.2023",
    "totalOrders": 14,
    "totalRevenue": 11059,
    "fullName": "Савельева Анастасия Ивановна"
  },
  {
    "id": 9,
    "login": "loginqueen",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/5.jpg",
    "gender": false,
    "email": "olivia.miller@example.com",
    "phone": "75934174880",
    "country": "Россия",
    "role": "Заблокирован",
    "dateOfBirth": "21.09.2006",
    "dateOfRegistration": "07.10.2022",
    "totalOrders": 20,
    "totalRevenue": 22782,
    "fullName": "Лазарева Анастасия Александровна"
  },
  {
    "id": 10,
    "login": "test123",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/1.jpg",
    "gender": true,
    "email": "ava.martinez@example.com",
    "phone": "81461696833",
    "country": "Белоруссия",
    "role": "Покупатель",
    "dateOfBirth": "18.09.2005",
    "dateOfRegistration": "25.10.2020",
    "totalOrders": 6,
    "totalRevenue": 73871,
    "fullName": "Дмитриев Сергей Владимирович"
  },
  {
    "id": 11,
    "login": "testuser",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/3.jpg",
    "gender": false,
    "email": "ava.martinez@example.com",
    "phone": "70401854331",
    "country": "Белоруссия",
    "role": "Заблокирован",
    "dateOfBirth": "29.10.2008",
    "dateOfRegistration": "29.06.2022",
    "totalOrders": 19,
    "totalRevenue": 15537,
    "fullName": "Лебедева Анастасия Сергеевна"
  },
  {
    "id": 12,
    "login": "loginqueen",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/1.jpg",
    "gender": false,
    "email": "ethan.martinez@example.com",
    "phone": "87263841145",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "19.02.2008",
    "dateOfRegistration": "02.02.2024",
    "totalOrders": 2,
    "totalRevenue": 59209,
    "fullName": "Калашников Иван Степанович"
  },
  {
    "id": 13,
    "login": "usermaster",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/1.jpg",
    "gender": true,
    "email": "noah.morris@example.com",
    "phone": "77357710005",
    "country": "Другая",
    "role": "Администратор",
    "dateOfBirth": "23.06.2001",
    "dateOfRegistration": "11.02.2022",
    "totalOrders": 20,
    "totalRevenue": 80354,
    "fullName": "Смирнова Екатерина Александровна"
  },
  {
    "id": 14,
    "login": "guestlogin",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/3.jpg",
    "gender": true,
    "email": "logan.collins@example.com",
    "phone": "78179007762",
    "country": "Другая",
    "role": "Менеджер",
    "dateOfBirth": "17.10.2001",
    "dateOfRegistration": "15.05.2024",
    "totalOrders": 16,
    "totalRevenue": 52593,
    "fullName": "Мартынов Денис Викторович"
  },
  {
    "id": 15,
    "login": "superuser",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/4.jpg",
    "gender": false,
    "email": "luke.lee@example.com",
    "phone": "70746143338",
    "country": "Казахстан",
    "role": "Заблокирован",
    "dateOfBirth": "23.04.2000",
    "dateOfRegistration": "17.11.2022",
    "totalOrders": 4,
    "totalRevenue": 96571,
    "fullName": "Макаров Илья Петрович"
  },
  {
    "id": 16,
    "login": "testaccount",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/3.jpg",
    "gender": false,
    "email": "emily.wilson@example.com",
    "phone": "74726768146",
    "country": "Белоруссия",
    "role": "Менеджер",
    "dateOfBirth": "11.11.2008",
    "dateOfRegistration": "23.07.2023",
    "totalOrders": 1,
    "totalRevenue": 32614,
    "fullName": "Макаров Илья Петрович"
  },
  {
    "id": 17,
    "login": "login456",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/4.jpg",
    "gender": false,
    "email": "ava.miller@example.com",
    "phone": "89572258154",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "07.06.2006",
    "dateOfRegistration": "06.08.2022",
    "totalOrders": 10,
    "totalRevenue": 2002,
    "fullName": "Соколова Мария Алексеевна"
  },
  {
    "id": 18,
    "login": "testuser",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/3.jpg",
    "gender": false,
    "email": "david.brown@example.com",
    "phone": "78054930141",
    "country": "Россия",
    "role": "Менеджер",
    "dateOfBirth": "28.03.2005",
    "dateOfRegistration": "21.04.2021",
    "totalOrders": 9,
    "totalRevenue": 42620,
    "fullName": "Федоров Владислав Сергеевич"
  },
  {
    "id": 19,
    "login": "testuser",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/5.jpg",
    "gender": false,
    "email": "liam.baker@example.com",
    "phone": "74146864167",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "14.09.2004",
    "dateOfRegistration": "15.09.2020",
    "totalOrders": 11,
    "totalRevenue": 95633,
    "fullName": "Павлова Елена Дмитриевна"
  },
  {
    "id": 20,
    "login": "guestuser",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/1.jpg",
    "gender": true,
    "email": "daniel.roberts@example.com",
    "phone": "71838727400",
    "country": "Казахстан",
    "role": "Менеджер",
    "dateOfBirth": "29.04.2000",
    "dateOfRegistration": "20.11.2020",
    "totalOrders": 12,
    "totalRevenue": 49096,
    "fullName": "Костина Елена Алексеевна"
  },
  {
    "id": 21,
    "login": "user1234",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/2.jpg",
    "gender": true,
    "email": "oliver.wood@example.com",
    "phone": "71956672962",
    "country": "Армения",
    "role": "Менеджер",
    "dateOfBirth": "28.11.2000",
    "dateOfRegistration": "02.11.2020",
    "totalOrders": 3,
    "totalRevenue": 64023,
    "fullName": "Зайцева Алина Сергеевна"
  },
  {
    "id": 22,
    "login": "userlogin123",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/3.jpg",
    "gender": true,
    "email": "ava.miller@example.com",
    "phone": "72129441739",
    "country": "Грузия",
    "role": "Менеджер",
    "dateOfBirth": "29.10.2005",
    "dateOfRegistration": "20.08.2021",
    "totalOrders": 6,
    "totalRevenue": 8770,
    "fullName": "Орлов Дмитрий Андреевич"
  },
  {
    "id": 23,
    "login": "johnsmith",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/5.jpg",
    "gender": true,
    "email": "mason.lee@example.com",
    "phone": "81203624121",
    "country": "Белоруссия",
    "role": "Менеджер",
    "dateOfBirth": "28.02.2001",
    "dateOfRegistration": "12.12.2022",
    "totalOrders": 8,
    "totalRevenue": 72903,
    "fullName": "Васильев Андрей Игоревич"
  },
  {
    "id": 24,
    "login": "newbie",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/1.jpg",
    "gender": false,
    "email": "michael.wilson@example.com",
    "phone": "71516370724",
    "country": "Россия",
    "role": "Менеджер",
    "dateOfBirth": "05.06.2001",
    "dateOfRegistration": "03.03.2021",
    "totalOrders": 5,
    "totalRevenue": 98574,
    "fullName": "Лапина Анастасия Павловна"
  },
  {
    "id": 25,
    "login": "newbie",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/4.jpg",
    "gender": false,
    "email": "chloe.robinson@example.com",
    "phone": "83100763722",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "05.02.2001",
    "dateOfRegistration": "15.02.2023",
    "totalOrders": 17,
    "totalRevenue": 54321,
    "fullName": "Лапина Анастасия Павловна"
  },
  {
    "id": 26,
    "login": "user1",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/1.jpg",
    "gender": true,
    "email": "james.davis@example.com",
    "phone": "81905798521",
    "country": "Другая",
    "role": "Администратор",
    "dateOfBirth": "15.07.2007",
    "dateOfRegistration": "06.10.2020",
    "totalOrders": 4,
    "totalRevenue": 69414,
    "fullName": "Герасимова Татьяна Сергеевна"
  },
  {
    "id": 27,
    "login": "codinglogin",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/1.jpg",
    "gender": false,
    "email": "hannah.white@example.com",
    "phone": "72513745477",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "04.09.2007",
    "dateOfRegistration": "20.08.2021",
    "totalOrders": 7,
    "totalRevenue": 1698,
    "fullName": "Макаров Илья Петрович"
  },
  {
    "id": 28,
    "login": "coollogin",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/5.jpg",
    "gender": false,
    "email": "alexander.jones@example.com",
    "phone": "81616592897",
    "country": "Белоруссия",
    "role": "Администратор",
    "dateOfBirth": "07.08.2004",
    "dateOfRegistration": "11.09.2022",
    "totalOrders": 3,
    "totalRevenue": 98540,
    "fullName": "Лебедева Анастасия Сергеевна"
  },
  {
    "id": 29,
    "login": "jane_smith",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/4.jpg",
    "gender": false,
    "email": "lucas.roberts@example.com",
    "phone": "81018616750",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "27.05.2007",
    "dateOfRegistration": "13.09.2020",
    "totalOrders": 11,
    "totalRevenue": 94455,
    "fullName": "Васильев Андрей Игоревич"
  },
  {
    "id": 30,
    "login": "usermaster",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/2.jpg",
    "gender": false,
    "email": "michael.nguyen@example.com",
    "phone": "79484756754",
    "country": "Казахстан",
    "role": "Менеджер",
    "dateOfBirth": "05.10.2003",
    "dateOfRegistration": "07.02.2022",
    "totalOrders": 8,
    "totalRevenue": 5698,
    "fullName": "Иванов Иван Иванович"
  },
  {
    "id": 31,
    "login": "user123",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/4.jpg",
    "gender": true,
    "email": "alexander.jones@example.com",
    "phone": "84952485524",
    "country": "Грузия",
    "role": "Администратор",
    "dateOfBirth": "20.02.2006",
    "dateOfRegistration": "26.06.2022",
    "totalOrders": 18,
    "totalRevenue": 3160,
    "fullName": "Федоров Владислав Сергеевич"
  },
  {
    "id": 32,
    "login": "user1234",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/1.jpg",
    "gender": true,
    "email": "mia.stewart@example.com",
    "phone": "85839918003",
    "country": "Россия",
    "role": "Администратор",
    "dateOfBirth": "20.09.2007",
    "dateOfRegistration": "27.05.2024",
    "totalOrders": 4,
    "totalRevenue": 44588,
    "fullName": "Семенов Денис Николаевич"
  },
  {
    "id": 33,
    "login": "guest123",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/4.jpg",
    "gender": true,
    "email": "daniel.roberts@example.com",
    "phone": "72717954746",
    "country": "Россия",
    "role": "Покупатель",
    "dateOfBirth": "11.06.2009",
    "dateOfRegistration": "06.09.2021",
    "totalOrders": 14,
    "totalRevenue": 62949,
    "fullName": "Герасимова Татьяна Сергеевна"
  },
  {
    "id": 34,
    "login": "loginadmin",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/3.jpg",
    "gender": true,
    "email": "michael.wilson@example.com",
    "phone": "86402364118",
    "country": "Грузия",
    "role": "Администратор",
    "dateOfBirth": "14.11.2002",
    "dateOfRegistration": "30.04.2021",
    "totalOrders": 20,
    "totalRevenue": 27782,
    "fullName": "Лазарева Анастасия Александровна"
  },
  {
    "id": 35,
    "login": "testuser123",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/5.jpg",
    "gender": false,
    "email": "michael.wilson@example.com",
    "phone": "75855724125",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "07.02.2009",
    "dateOfRegistration": "20.08.2021",
    "totalOrders": 18,
    "totalRevenue": 61835,
    "fullName": "Козлов Дмитрий Павлович"
  },
  {
    "id": 36,
    "login": "janedoe",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/2.jpg",
    "gender": false,
    "email": "matthew.nguyen@example.com",
    "phone": "86818404079",
    "country": "Армения",
    "role": "Администратор",
    "dateOfBirth": "05.02.2006",
    "dateOfRegistration": "22.12.2023",
    "totalOrders": 16,
    "totalRevenue": 1949,
    "fullName": "Медведева Виктория Алексеевна"
  },
  {
    "id": 37,
    "login": "userlogin",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/3.jpg",
    "gender": false,
    "email": "william.gonzalez@example.com",
    "phone": "79198138372",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "02.08.2009",
    "dateOfRegistration": "06.07.2021",
    "totalOrders": 16,
    "totalRevenue": 77120,
    "fullName": "Иванов Иван Иванович"
  },
  {
    "id": 38,
    "login": "codingwizard",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/2.jpg",
    "gender": false,
    "email": "mia.stewart@example.com",
    "phone": "71831142585",
    "country": "Россия",
    "role": "Менеджер",
    "dateOfBirth": "26.09.2006",
    "dateOfRegistration": "01.10.2022",
    "totalOrders": 6,
    "totalRevenue": 49944,
    "fullName": "Тимофеева Марина Владимировна"
  },
  {
    "id": 39,
    "login": "john_doe",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/3.jpg",
    "gender": true,
    "email": "zoey.adams@example.com",
    "phone": "81010776902",
    "country": "Казахстан",
    "role": "Заблокирован",
    "dateOfBirth": "21.10.2000",
    "dateOfRegistration": "10.04.2021",
    "totalOrders": 6,
    "totalRevenue": 27265,
    "fullName": "Морозова Ольга Владимировна"
  },
  {
    "id": 40,
    "login": "techguru",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/5.jpg",
    "gender": true,
    "email": "olivia.rodriguez@example.com",
    "phone": "79809770027",
    "country": "Армения",
    "role": "Покупатель",
    "dateOfBirth": "12.05.2009",
    "dateOfRegistration": "03.04.2024",
    "totalOrders": 14,
    "totalRevenue": 2651,
    "fullName": "Захарова Алина Алексеевна"
  },
  {
    "id": 41,
    "login": "loginadmin",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/3.jpg",
    "gender": false,
    "email": "isabella.johnson@example.com",
    "phone": "81043247719",
    "country": "Армения",
    "role": "Заблокирован",
    "dateOfBirth": "19.05.2009",
    "dateOfRegistration": "10.06.2022",
    "totalOrders": 20,
    "totalRevenue": 29336,
    "fullName": "Григорьева Валерия Александровна"
  },
  {
    "id": 42,
    "login": "testuser123",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/4.jpg",
    "gender": false,
    "email": "oliver.wood@example.com",
    "phone": "83594381125",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "27.02.2002",
    "dateOfRegistration": "16.03.2022",
    "totalOrders": 20,
    "totalRevenue": 61332,
    "fullName": "Тимофеева Марина Владимировна"
  },
  {
    "id": 43,
    "login": "test123",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/2.jpg",
    "gender": false,
    "email": "lucas.roberts@example.com",
    "phone": "88580899212",
    "country": "Другая",
    "role": "Администратор",
    "dateOfBirth": "15.10.2000",
    "dateOfRegistration": "01.07.2024",
    "totalOrders": 10,
    "totalRevenue": 74291,
    "fullName": "Медведева Виктория Алексеевна"
  },
  {
    "id": 44,
    "login": "loginuser",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/5.jpg",
    "gender": true,
    "email": "michael.nguyen@example.com",
    "phone": "80374203672",
    "country": "Армения",
    "role": "Администратор",
    "dateOfBirth": "21.10.2009",
    "dateOfRegistration": "11.11.2021",
    "totalOrders": 6,
    "totalRevenue": 59639,
    "fullName": "Игнатьев Артем Васильевич"
  },
  {
    "id": 45,
    "login": "login456",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/3.jpg",
    "gender": false,
    "email": "daniel.roberts@example.com",
    "phone": "80553603430",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "16.09.2001",
    "dateOfRegistration": "18.06.2021",
    "totalOrders": 7,
    "totalRevenue": 26530,
    "fullName": "Королева Анна Игоревна"
  },
  {
    "id": 46,
    "login": "user007",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/men/4.jpg",
    "gender": false,
    "email": "john.doe@example.com",
    "phone": "72601060713",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "09.08.2007",
    "dateOfRegistration": "06.04.2023",
    "totalOrders": 7,
    "totalRevenue": 39512,
    "fullName": "Кудрявцева Мария Александровна"
  },
  {
    "id": 47,
    "login": "techuser",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/3.jpg",
    "gender": false,
    "email": "william.gonzalez@example.com",
    "phone": "76769059140",
    "country": "Армения",
    "role": "Заблокирован",
    "dateOfBirth": "30.04.2010",
    "dateOfRegistration": "21.06.2021",
    "totalOrders": 12,
    "totalRevenue": 24023,
    "fullName": "Кириллов Игорь Павлович"
  },
  {
    "id": 48,
    "login": "login2",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/4.jpg",
    "gender": false,
    "email": "sophia.rodriguez@example.com",
    "phone": "83058942622",
    "country": "Белоруссия",
    "role": "Менеджер",
    "dateOfBirth": "03.10.2002",
    "dateOfRegistration": "18.11.2021",
    "totalOrders": 10,
    "totalRevenue": 56051,
    "fullName": "Петров Александр Сергеевич"
  },
  {
    "id": 49,
    "login": "userlogin123",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/women/1.jpg",
    "gender": true,
    "email": "jane.smith@example.com",
    "phone": "85164364549",
    "country": "Другая",
    "role": "Менеджер",
    "dateOfBirth": "01.02.2005",
    "dateOfRegistration": "06.10.2023",
    "totalOrders": 2,
    "totalRevenue": 60925,
    "fullName": "Григорьева Валерия Александровна"
  },
  {
    "id": 50,
    "login": "janedoe",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/4.jpg",
    "gender": true,
    "email": "noah.morris@example.com",
    "phone": "82789162500",
    "country": "Грузия",
    "role": "Администратор",
    "dateOfBirth": "08.07.2006",
    "dateOfRegistration": "07.05.2022",
    "totalOrders": 7,
    "totalRevenue": 95117,
    "fullName": "Калашников Иван Степанович"
  },
  {
    "id": 51,
    "login": "janedoe",
    "isActive": false,
    "avatar": "https://randomuser.me/api/portraits/women/4.jpg",
    "gender": false,
    "email": "chloe.robinson@example.com",
    "phone": "71191281058",
    "country": "Белоруссия",
    "role": "Покупатель",
    "dateOfBirth": "20.07.2001",
    "dateOfRegistration": "19.03.2024",
    "totalOrders": 9,
    "totalRevenue": 87794,
    "fullName": "Лапина Анастасия Павловна"
  },
  {
    "id": 52,
    "login": "usermaster",
    "isActive": true,
    "avatar": "https://randomuser.me/api/portraits/men/4.jpg",
    "gender": false,
    "email": "mason.lee@example.com",
    "phone": "72306219743",
    "country": "Другая",
    "role": "Заблокирован",
    "dateOfBirth": "03.11.2000",
    "dateOfRegistration": "18.12.2023",
    "totalOrders": 6,
    "totalRevenue": 11513,
    "fullName": "Гаврилова Елизавета Андреевна"
  }
];