import type { IUser } from "./interfaces/IUser";


export const USERS: IUser[] = [
  {
    "id": 1,
    "login": "jkrienke0",
    "isActive": true,
    "avatar": "https://robohash.org/modiutreiciendis.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "79777419457",
    "country": "Армения",
    "role": "Покупатель",
    "dateOfBirth": "12.11.2008",
    "dateOfRegistration": "24.05.2024"
  },
  {
    "id": 2,
    "login": "ahedling1",
    "isActive": false,
    "avatar": "https://robohash.org/delenitiquamaut.png?size=50x50&set=set1",
    "gender": true,
    "email": "example3@mail.ru",
    "phone": "|9019327316",
    "country": "Россия",
    "role": "Покупатель",
    "dateOfBirth": "04.01.2010",
    "dateOfRegistration": "12.03.2023"
  },
  {
    "id": 3,
    "login": "kcasaccio2",
    "isActive": false,
    "avatar": "https://robohash.org/blanditiisevenietratione.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "79442276446",
    "country": "Грузия",
    "role": "Менеджер",
    "dateOfBirth": "07.11.2008",
    "dateOfRegistration": "02.04.2024"
  },
  {
    "id": 4,
    "login": "msimeoli3",
    "isActive": false,
    "avatar": "https://robohash.org/nonmagniut.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "89453375133",
    "country": "Казахстан",
    "role": "Покупатель",
    "dateOfBirth": "24.05.2009",
    "dateOfRegistration": "21.05.2023"
  },
  {
    "id": 5,
    "login": "jokieran4",
    "isActive": false,
    "avatar": "https://robohash.org/commodiquiabeatae.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "79332612478",
    "country": "Белоруссия",
    "role": "Менеджер",
    "dateOfBirth": "10.07.2009",
    "dateOfRegistration": "05.08.2022"
  },
  {
    "id": 6,
    "login": "dhalbeard5",
    "isActive": false,
    "avatar": "https://robohash.org/quovoluptasvoluptas.png?size=50x50&set=set1",
    "gender": true,
    "email": "example3@mail.ru",
    "phone": "89540696316",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "12.06.2003",
    "dateOfRegistration": "10.08.2023"
  },
  {
    "id": 7,
    "login": "bfishbie6",
    "isActive": true,
    "avatar": "https://robohash.org/maximererumvoluptates.png?size=50x50&set=set1",
    "gender": true,
    "email": "example3@mail.ru",
    "phone": "79289456369",
    "country": "Грузия",
    "role": "Менеджер",
    "dateOfBirth": "21.01.2008",
    "dateOfRegistration": "25.06.2024"
  },
  {
    "id": 8,
    "login": "cfarnish7",
    "isActive": true,
    "avatar": "https://robohash.org/sedreiciendisnihil.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "89221979029",
    "country": "Грузия",
    "role": "Менеджер",
    "dateOfBirth": "11.04.2009",
    "dateOfRegistration": "21.06.2024"
  },
  {
    "id": 9,
    "login": "msibary8",
    "isActive": true,
    "avatar": "https://robohash.org/voluptatequaeratomnis.png?size=50x50&set=set1",
    "gender": true,
    "email": "example3@mail.ru",
    "phone": "89096554454",
    "country": "Белоруссия",
    "role": "Администратор",
    "dateOfBirth": "20.02.2002",
    "dateOfRegistration": "19.02.2023"
  },
  {
    "id": 10,
    "login": "chewkin9",
    "isActive": true,
    "avatar": "https://robohash.org/officiaminimased.png?size=50x50&set=set1",
    "gender": true,
    "email": "example2@gmail.com",
    "phone": "|9884921423",
    "country": "Россия",
    "role": "Заблокирован",
    "dateOfBirth": "04.10.2005",
    "dateOfRegistration": "18.06.2023"
  },
  {
    "id": 11,
    "login": "mdorseta",
    "isActive": false,
    "avatar": "https://robohash.org/etnobisofficiis.png?size=50x50&set=set1",
    "gender": false,
    "email": "example3@mail.ru",
    "phone": "|9470594816",
    "country": "Россия",
    "role": "Администратор",
    "dateOfBirth": "10.07.2010",
    "dateOfRegistration": "25.12.2023"
  },
  {
    "id": 12,
    "login": "ecareb",
    "isActive": false,
    "avatar": "https://robohash.org/impeditetquis.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "89061664600",
    "country": "Белоруссия",
    "role": "Администратор",
    "dateOfBirth": "28.11.2001",
    "dateOfRegistration": "04.09.2023"
  },
  {
    "id": 13,
    "login": "cbeallc",
    "isActive": true,
    "avatar": "https://robohash.org/evenietasperioresdolore.png?size=50x50&set=set1",
    "gender": false,
    "email": "example3@mail.ru",
    "phone": "79695435288",
    "country": "Белоруссия",
    "role": "Покупатель",
    "dateOfBirth": "10.04.2007",
    "dateOfRegistration": "18.02.2024"
  },
  {
    "id": 14,
    "login": "kreisenbergd",
    "isActive": true,
    "avatar": "https://robohash.org/voluptatuminventoreet.png?size=50x50&set=set1",
    "gender": true,
    "email": "example3@mail.ru",
    "phone": "|9880070786",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "21.09.2000",
    "dateOfRegistration": "22.10.2023"
  },
  {
    "id": 15,
    "login": "lmilligane",
    "isActive": false,
    "avatar": "https://robohash.org/etconsequaturvoluptatem.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "79745470655",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "24.09.2004",
    "dateOfRegistration": "04.04.2023"
  },
  {
    "id": 16,
    "login": "wbraunef",
    "isActive": false,
    "avatar": "https://robohash.org/velitoditfacere.png?size=50x50&set=set1",
    "gender": false,
    "email": "example3@mail.ru",
    "phone": "|9473002900",
    "country": "Армения",
    "role": "Менеджер",
    "dateOfBirth": "14.01.2006",
    "dateOfRegistration": "16.11.2023"
  },
  {
    "id": 17,
    "login": "jrubinowitzg",
    "isActive": true,
    "avatar": "https://robohash.org/voluptateetalias.png?size=50x50&set=set1",
    "gender": false,
    "email": "example1@yandex.ru",
    "phone": "|9627474906",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "03.05.2006",
    "dateOfRegistration": "13.06.2023"
  },
  {
    "id": 18,
    "login": "ibeddallh",
    "isActive": false,
    "avatar": "https://robohash.org/omnisconsequaturvoluptate.png?size=50x50&set=set1",
    "gender": false,
    "email": "example1@yandex.ru",
    "phone": "89780551640",
    "country": "Грузия",
    "role": "Администратор",
    "dateOfBirth": "19.06.2001",
    "dateOfRegistration": "10.08.2022"
  },
  {
    "id": 19,
    "login": "ctolcheri",
    "isActive": false,
    "avatar": "https://robohash.org/erroretsimilique.png?size=50x50&set=set1",
    "gender": true,
    "email": "example3@mail.ru",
    "phone": "79719386342",
    "country": "Другая",
    "role": "Покупатель",
    "dateOfBirth": "27.04.2000",
    "dateOfRegistration": "12.09.2022"
  },
  {
    "id": 20,
    "login": "adunstonj",
    "isActive": false,
    "avatar": "https://robohash.org/autestquo.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "79023174471",
    "country": "Россия",
    "role": "Менеджер",
    "dateOfBirth": "21.07.2010",
    "dateOfRegistration": "31.05.2023"
  },
  {
    "id": 21,
    "login": "csivillsk",
    "isActive": true,
    "avatar": "https://robohash.org/nequecorporisrepudiandae.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "79839283702",
    "country": "Россия",
    "role": "Покупатель",
    "dateOfBirth": "12.02.2000",
    "dateOfRegistration": "10.11.2022"
  },
  {
    "id": 22,
    "login": "egeharkel",
    "isActive": false,
    "avatar": "https://robohash.org/atevenietexplicabo.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "79358096069",
    "country": "Белоруссия",
    "role": "Менеджер",
    "dateOfBirth": "20.06.2006",
    "dateOfRegistration": "17.04.2024"
  },
  {
    "id": 23,
    "login": "sburtwellm",
    "isActive": true,
    "avatar": "https://robohash.org/nostrummolestiaeesse.png?size=50x50&set=set1",
    "gender": true,
    "email": "example3@mail.ru",
    "phone": "79840653466",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "29.09.1999",
    "dateOfRegistration": "10.11.2023"
  },
  {
    "id": 24,
    "login": "gberginn",
    "isActive": false,
    "avatar": "https://robohash.org/quiaspernaturqui.png?size=50x50&set=set1",
    "gender": true,
    "email": "example2@gmail.com",
    "phone": "|9136104025",
    "country": "Грузия",
    "role": "Покупатель",
    "dateOfBirth": "17.05.2002",
    "dateOfRegistration": "12.12.2023"
  },
  {
    "id": 25,
    "login": "mwattamo",
    "isActive": true,
    "avatar": "https://robohash.org/quoporrodelectus.png?size=50x50&set=set1",
    "gender": false,
    "email": "example1@yandex.ru",
    "phone": "|9658945593",
    "country": "Грузия",
    "role": "Менеджер",
    "dateOfBirth": "18.10.2007",
    "dateOfRegistration": "14.10.2022"
  },
  {
    "id": 26,
    "login": "smeeganp",
    "isActive": false,
    "avatar": "https://robohash.org/porromagnidelectus.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "89787404880",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "08.08.2005",
    "dateOfRegistration": "24.05.2024"
  },
  {
    "id": 27,
    "login": "akleynenq",
    "isActive": false,
    "avatar": "https://robohash.org/solutaillumcumque.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "89308633893",
    "country": "Грузия",
    "role": "Заблокирован",
    "dateOfBirth": "28.01.2002",
    "dateOfRegistration": "11.11.2022"
  },
  {
    "id": 28,
    "login": "fbussonsr",
    "isActive": false,
    "avatar": "https://robohash.org/voluptateexpeditaaut.png?size=50x50&set=set1",
    "gender": true,
    "email": "example2@gmail.com",
    "phone": "89098191142",
    "country": "Армения",
    "role": "Заблокирован",
    "dateOfBirth": "08.08.1999",
    "dateOfRegistration": "30.06.2023"
  },
  {
    "id": 29,
    "login": "edesforgess",
    "isActive": true,
    "avatar": "https://robohash.org/deserunteumnobis.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "79624012334",
    "country": "Казахстан",
    "role": "Покупатель",
    "dateOfBirth": "14.07.2001",
    "dateOfRegistration": "01.08.2024"
  },
  {
    "id": 30,
    "login": "efrankcomt",
    "isActive": false,
    "avatar": "https://robohash.org/ipsumevenietaccusantium.png?size=50x50&set=set1",
    "gender": false,
    "email": "example3@mail.ru",
    "phone": "|9117478444",
    "country": "Казахстан",
    "role": "Менеджер",
    "dateOfBirth": "13.02.2003",
    "dateOfRegistration": "16.11.2022"
  },
  {
    "id": 31,
    "login": "abunneru",
    "isActive": true,
    "avatar": "https://robohash.org/assumendalaboreinventore.png?size=50x50&set=set1",
    "gender": true,
    "email": "example2@gmail.com",
    "phone": "79054113198",
    "country": "Другая",
    "role": "Менеджер",
    "dateOfBirth": "16.07.2008",
    "dateOfRegistration": "12.02.2023"
  },
  {
    "id": 32,
    "login": "mpiggensv",
    "isActive": false,
    "avatar": "https://robohash.org/quascumtempore.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "89077325184",
    "country": "Россия",
    "role": "Заблокирован",
    "dateOfBirth": "06.01.2008",
    "dateOfRegistration": "04.11.2022"
  },
  {
    "id": 33,
    "login": "dmelrosew",
    "isActive": true,
    "avatar": "https://robohash.org/officiisquiomnis.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "|9455896238",
    "country": "Армения",
    "role": "Покупатель",
    "dateOfBirth": "08.11.2001",
    "dateOfRegistration": "16.05.2024"
  },
  {
    "id": 34,
    "login": "citzkowiczx",
    "isActive": false,
    "avatar": "https://robohash.org/fugaconsequunturest.png?size=50x50&set=set1",
    "gender": true,
    "email": "example2@gmail.com",
    "phone": "79904411390",
    "country": "Казахстан",
    "role": "Администратор",
    "dateOfBirth": "08.04.2000",
    "dateOfRegistration": "03.07.2023"
  },
  {
    "id": 35,
    "login": "rpebworthy",
    "isActive": true,
    "avatar": "https://robohash.org/utnihileligendi.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "79633599707",
    "country": "Белоруссия",
    "role": "Заблокирован",
    "dateOfBirth": "16.09.2005",
    "dateOfRegistration": "20.10.2022"
  },
  {
    "id": 36,
    "login": "bsimonouz",
    "isActive": true,
    "avatar": "https://robohash.org/etodiosuscipit.png?size=50x50&set=set1",
    "gender": false,
    "email": "example1@yandex.ru",
    "phone": "79963060740",
    "country": "Армения",
    "role": "Администратор",
    "dateOfBirth": "05.08.2001",
    "dateOfRegistration": "28.06.2023"
  },
  {
    "id": 37,
    "login": "tsansum10",
    "isActive": false,
    "avatar": "https://robohash.org/liberoundeaut.png?size=50x50&set=set1",
    "gender": false,
    "email": "example1@yandex.ru",
    "phone": "|9700242863",
    "country": "Белоруссия",
    "role": "Покупатель",
    "dateOfBirth": "20.06.2001",
    "dateOfRegistration": "05.07.2024"
  },
  {
    "id": 38,
    "login": "rmckue11",
    "isActive": true,
    "avatar": "https://robohash.org/autrerumnemo.png?size=50x50&set=set1",
    "gender": false,
    "email": "example3@mail.ru",
    "phone": "|9342529678",
    "country": "Россия",
    "role": "Менеджер",
    "dateOfBirth": "08.11.2004",
    "dateOfRegistration": "13.07.2024"
  },
  {
    "id": 39,
    "login": "ecaccavari12",
    "isActive": false,
    "avatar": "https://robohash.org/placeatquidemnisi.png?size=50x50&set=set1",
    "gender": false,
    "email": "example3@mail.ru",
    "phone": "89036336356",
    "country": "Армения",
    "role": "Покупатель",
    "dateOfBirth": "10.02.2007",
    "dateOfRegistration": "19.12.2022"
  },
  {
    "id": 40,
    "login": "dgostick13",
    "isActive": false,
    "avatar": "https://robohash.org/totamomnisiste.png?size=50x50&set=set1",
    "gender": true,
    "email": "example3@mail.ru",
    "phone": "89603178303",
    "country": "Россия",
    "role": "Заблокирован",
    "dateOfBirth": "22.10.2003",
    "dateOfRegistration": "30.04.2024"
  },
  {
    "id": 41,
    "login": "nkeam14",
    "isActive": true,
    "avatar": "https://robohash.org/rationeipsamofficia.png?size=50x50&set=set1",
    "gender": false,
    "email": "example2@gmail.com",
    "phone": "89744517016",
    "country": "Армения",
    "role": "Менеджер",
    "dateOfBirth": "15.08.2000",
    "dateOfRegistration": "21.04.2023"
  },
  {
    "id": 42,
    "login": "bsoames15",
    "isActive": false,
    "avatar": "https://robohash.org/rerumaccusantiumarchitecto.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "79849032152",
    "country": "Армения",
    "role": "Заблокирован",
    "dateOfBirth": "13.07.2003",
    "dateOfRegistration": "04.07.2024"
  },
  {
    "id": 43,
    "login": "rwollrauch16",
    "isActive": true,
    "avatar": "https://robohash.org/repellendusfugiatplaceat.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "79132083007",
    "country": "Другая",
    "role": "Менеджер",
    "dateOfBirth": "11.03.2003",
    "dateOfRegistration": "18.01.2023"
  },
  {
    "id": 44,
    "login": "sdyde17",
    "isActive": false,
    "avatar": "https://robohash.org/autemquiavoluptatum.png?size=50x50&set=set1",
    "gender": true,
    "email": "example1@yandex.ru",
    "phone": "79220730150",
    "country": "Казахстан",
    "role": "Заблокирован",
    "dateOfBirth": "12.09.2006",
    "dateOfRegistration": "01.11.2022"
  },
  {
    "id": 45,
    "login": "ejohnson18",
    "isActive": false,
    "avatar": "https://robohash.org/temporealiasomnis.png?size=50x50&set=set1",
    "gender": false,
    "email": "example3@mail.ru",
    "phone": "79794284395",
    "country": "Казахстан",
    "role": "Заблокирован",
    "dateOfBirth": "02.09.2006",
    "dateOfRegistration": "11.06.2023"
  },
	{
		"id": 46,
		"isActive": true,
		"avatar": "/src/assets/images/avatar.png",
		"login": "midi",
		"gender": true,
		"email": "testtest@mail.ru",
		"phone": "79626373903",
		"country": "Россия",
		"role": "Покупатель",
		"dateOfBirth": "30.08.2003",
		"dateOfRegistration": "26.07.2024"
	}
];